arrival_time = "16:41:00"
departure_time = "16:41:00"
destination_code = "Universal - Studio City Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "224"
stop_headsign = "224 - Universal - Studio City Station"
stop_id = "2811"
stop_sequence = "39"
timepoint = "0"
trip_id = "70224002661555-JUNE22"
trip_id_event = "55790657-JUNE22-D15CAR-3_Sunday"
