arrival_time = "16:48:00"
departure_time = "16:48:00"
destination_code = "Downtown LA - 6th - Los Angeles"
drop_off_type = "0"
pickup_type = "0"
route_code = "16"
stop_headsign = "16 - Downtown LA - 6th - Los Angeles"
stop_id = "7281"
stop_sequence = "30"
timepoint = "0"
trip_id = "10016004191557-JUNE22"
trip_id_event = "55885134-JUNE22-D07CAR-1_Weekday"
