arrival_time = "10:15:00"
departure_time = "10:15:00"
destination_code = "Avalon Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "51"
stop_headsign = "51 - Avalon Station"
stop_id = "265"
stop_sequence = "50"
timepoint = "0"
trip_id = "10051003270919-JUNE22"
trip_id_event = "55982707-JUNE22-D02CAR-1_Weekday"
