arrival_time = "20:30:00"
departure_time = "20:30:00"
destination_code = "El Monte Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "76"
stop_headsign = "76 - El Monte Station"
stop_id = "3241"
stop_sequence = "16"
timepoint = "0"
trip_id = "70076001912012-JUNE22"
trip_id_event = "55851063-JUNE22-D09CAR-3_Sunday"
