arrival_time = "05:26:00"
departure_time = "05:26:00"
destination_code = "Hollywood - Vine Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "210"
stop_headsign = "210 - Hollywood - Vine Station"
stop_id = "4986"
stop_sequence = "2"
timepoint = "0"
trip_id = "10210002980524-JUNE22"
trip_id_event = "55893531-JUNE22-D18CAR-1_Weekday"
