arrival_time = "08:19:00"
departure_time = "08:19:00"
destination_code = "Downtown LA - 6th - Los Angeles"
drop_off_type = "0"
pickup_type = "0"
route_code = "16"
stop_headsign = "16 - Downtown LA - 6th - Los Angeles"
stop_id = "7289"
stop_sequence = "32"
timepoint = "0"
trip_id = "10016004190745-JUNE22"
trip_id_event = "55885274-JUNE22-D07CAR-1_Weekday"
