arrival_time = "05:57:00"
departure_time = "05:57:00"
destination_code = "Westwood (Rapid)"
drop_off_type = "0"
pickup_type = "0"
route_code = "720"
stop_headsign = "720 - Westwood (Rapid)"
stop_id = "72000003"
stop_sequence = "6"
timepoint = "0"
trip_id = "10720012780547-JUNE22"
trip_id_event = "55978464-JUNE22-D13CAR-1_Weekday"
