arrival_time = "18:09:00"
departure_time = "18:09:00"
destination_code = "West LA - Sepulveda Blvd"
drop_off_type = "0"
pickup_type = "0"
route_code = "4"
stop_headsign = "4 - West LA - Sepulveda Blvd"
stop_id = "14405"
stop_sequence = "34"
timepoint = "0"
trip_id = "60004003171727-JUNE22"
trip_id_event = "55946577-JUNE22-D07CAR-2_Saturday"
