arrival_time = "14:32:00"
departure_time = "14:32:00"
destination_code = "Vermont / Athens Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "204"
stop_headsign = "204 - Vermont / Athens Station"
stop_id = "12457"
stop_sequence = "5"
timepoint = "0"
trip_id = "10204001221426-JUNE22"
trip_id_event = "55971066-JUNE22-D05CAR-1_Weekday"
