arrival_time = "21:07:00"
departure_time = "21:07:00"
destination_code = "Vermont / Sunset Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "204"
stop_headsign = "204 - Vermont / Sunset Station"
stop_id = "7092"
stop_sequence = "65"
timepoint = "1"
trip_id = "10204001151958-JUNE22"
trip_id_event = "55971010-JUNE22-D05CAR-1_Weekday"
