arrival_time = "14:42:00"
departure_time = "14:42:00"
destination_code = "Expo Park / USC Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "2"
stop_headsign = "2 - Expo Park / USC Station"
stop_id = "6403"
stop_sequence = "11"
timepoint = "0"
trip_id = "70002011261433-JUNE22"
trip_id_event = "55883924-JUNE22-D02CAR-3_Sunday"
