arrival_time = "15:34:00"
departure_time = "15:34:00"
destination_code = "El Monte Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "70"
stop_headsign = "70 - El Monte Station"
stop_id = "10647"
stop_sequence = "28"
timepoint = "0"
trip_id = "60070002941457-JUNE22"
trip_id_event = "55851410-JUNE22-D09CAR-2_Saturday"
