arrival_time = "13:46:00"
departure_time = "13:46:00"
destination_code = "Cal State Dominguez Hills"
drop_off_type = "0"
pickup_type = "0"
route_code = "53"
stop_headsign = "53 - Cal State Dominguez Hills"
stop_id = "13319"
stop_sequence = "31"
timepoint = "0"
trip_id = "70053002321303-JUNE22"
trip_id_event = "55825660-JUNE22-D01CAR-3_Sunday"
