arrival_time = "08:10:00"
departure_time = "08:10:00"
destination_code = "Las Tunas - Live Oak"
drop_off_type = "0"
pickup_type = "0"
route_code = "78"
stop_headsign = "78 - Las Tunas - Live Oak"
stop_id = "7778"
stop_sequence = "60"
timepoint = "0"
trip_id = "70078005190716-JUNE22"
trip_id_event = "55852231-JUNE22-D09CAR-3_Sunday"
