arrival_time = "07:54:00"
departure_time = "07:54:00"
destination_code = "Hollywood - Vine Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "180"
stop_headsign = "180 - Hollywood - Vine Station"
stop_id = "4749"
stop_sequence = "51"
timepoint = "0"
trip_id = "10180002390709-JUNE22"
trip_id_event = "55885580-JUNE22-D03CAR-1_Weekday"
