arrival_time = "20:25:00"
departure_time = "20:25:00"
destination_code = "LAX City Bus Center"
drop_off_type = "0"
pickup_type = "0"
route_code = "232"
stop_headsign = "232 - LAX City Bus Center"
stop_id = "13000045"
stop_sequence = "72"
timepoint = "0"
trip_id = "60232000891907-JUNE22"
trip_id_event = "56005114-JUNE22-D97-2_Saturday"
