arrival_time = "13:57:00"
departure_time = "13:57:00"
destination_code = "Downtown LA - Grand - Venice"
drop_off_type = "0"
pickup_type = "0"
route_code = "76"
stop_headsign = "76 - Downtown LA - Grand - Venice"
stop_id = "12275"
stop_sequence = "54"
timepoint = "0"
trip_id = "10076001921255-JUNE22"
trip_id_event = "55850849-JUNE22-D09CAR-1_Weekday"
