arrival_time = "12:24:00"
departure_time = "12:24:00"
destination_code = "Vermont / Athens Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "204"
stop_headsign = "204 - Vermont / Athens Station"
stop_id = "14027"
stop_sequence = "66"
timepoint = "0"
trip_id = "70204001221105-JUNE22"
trip_id_event = "55932715-JUNE22-D18CAR-3_Sunday"
