arrival_time = "20:02:00"
departure_time = "20:02:00"
destination_code = "Harbor Gateway Transit Center"
drop_off_type = "0"
pickup_type = "0"
route_code = "344"
stop_headsign = "344 - Harbor Gateway Transit Center"
stop_id = "2403"
stop_sequence = "24"
timepoint = "1"
trip_id = "60344000471943-JUNE22"
trip_id_event = "55894758-JUNE22-D18CAR-2_Saturday"
