arrival_time = "16:00:00"
departure_time = "16:00:00"
destination_code = "South Bay Galleria"
drop_off_type = "0"
pickup_type = "0"
route_code = "40"
stop_headsign = "40 - South Bay Galleria"
stop_id = "10903"
stop_sequence = "73"
timepoint = "0"
trip_id = "70040009161411-JUNE22"
trip_id_event = "55939973-JUNE22-D18CAR-3_Sunday"
