arrival_time = "12:52:00"
departure_time = "12:52:00"
destination_code = "Studio City"
drop_off_type = "0"
pickup_type = "0"
route_code = "230"
stop_headsign = "230 - Studio City"
stop_id = "2894"
stop_sequence = "22"
timepoint = "0"
trip_id = "10230000871228-JUNE22"
trip_id_event = "55961373-JUNE22-D15CAR-1_Weekday"
