arrival_time = "12:44:00"
departure_time = "12:44:00"
destination_code = "Downtown LA - Union Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "487"
stop_headsign = "487 - Downtown LA - Union Station"
stop_id = "12489"
stop_sequence = "34"
timepoint = "0"
trip_id = "10487001181212-JUNE22"
trip_id_event = "55850037-JUNE22-D09CAR-1_Weekday"
