arrival_time = "09:28:00"
departure_time = "09:28:00"
destination_code = "Harbor Gtwy TC via DTLA -J Line (Silver)"
drop_off_type = "0"
pickup_type = "0"
route_code = "910"
stop_headsign = "910 - Harbor Gtwy TC via DTLA -J Line (Silver)"
stop_id = "15820"
stop_sequence = "15"
timepoint = "0"
trip_id = "10910002100853-JUNE22"
trip_id_event = "55994938-JUNE22-D18CAR-1_Weekday"
