arrival_time = "05:44:00"
departure_time = "05:44:00"
destination_code = "Beverly Center"
drop_off_type = "0"
pickup_type = "0"
route_code = "37"
stop_headsign = "37 - Beverly Center"
stop_id = "56"
stop_sequence = "23"
timepoint = "1"
trip_id = "10014005020525-JUNE22"
trip_id_event = "55872750-JUNE22-D07CAR-1_Weekday"
