arrival_time = "18:09:00"
departure_time = "18:09:00"
destination_code = "Hawaiian Gardens - 226th - Norwalk Bldv"
drop_off_type = "0"
pickup_type = "0"
route_code = "62"
stop_headsign = "62 - Hawaiian Gardens - 226th - Norwalk Bldv"
stop_id = "5138"
stop_sequence = "5"
timepoint = "0"
trip_id = "70062003421759-JUNE22"
trip_id_event = "55825860-JUNE22-D01CAR-3_Sunday"
