arrival_time = "08:50:00"
departure_time = "08:50:00"
destination_code = "Harbor Gtwy TC via DTLA -J Line (Silver)"
drop_off_type = "0"
pickup_type = "0"
route_code = "910"
stop_headsign = "910 - Harbor Gtwy TC via DTLA -J Line (Silver)"
stop_id = "10994"
stop_sequence = "17"
timepoint = "0"
trip_id = "10910002100809-JUNE22"
trip_id_event = "55995039-JUNE22-D09CAR-1_Weekday"
