arrival_time = "16:31:00"
departure_time = "16:31:00"
destination_code = "Downtown LA - Union Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "40"
stop_headsign = "40 - Downtown LA - Union Station"
stop_id = "13242"
stop_sequence = "78"
timepoint = "0"
trip_id = "70040009111449-JUNE22"
trip_id_event = "55939932-JUNE22-D18CAR-3_Sunday"
