arrival_time = "13:02:00"
departure_time = "13:02:00"
destination_code = "San Pedro - Point Fermin"
drop_off_type = "0"
pickup_type = "0"
route_code = "246"
stop_headsign = "246 - San Pedro - Point Fermin"
stop_id = "13814"
stop_sequence = "61"
timepoint = "0"
trip_id = "70246000701208-JUNE22"
trip_id_event = "55894272-JUNE22-D18CAR-3_Sunday"
