arrival_time = "16:55:00"
departure_time = "16:55:00"
destination_code = "Downtown LA - 7th - Main"
drop_off_type = "0"
pickup_type = "0"
route_code = "33"
stop_headsign = "33 - Downtown LA - 7th - Main"
stop_id = "16404"
stop_sequence = "49"
timepoint = "0"
trip_id = "10033006191542-JUNE22"
trip_id_event = "55955125-JUNE22-D13CAR-1_Weekday"
