arrival_time = "17:44:00"
departure_time = "17:44:00"
destination_code = "Woodland Hills"
drop_off_type = "0"
pickup_type = "0"
route_code = "244"
stop_headsign = "244 - Woodland Hills"
stop_id = "984"
stop_sequence = "25"
timepoint = "0"
trip_id = "10244000021712-JUNE22"
trip_id_event = "55762550-JUNE22-D08CAR-1_Weekday"
