arrival_time = "21:54:00"
departure_time = "21:54:00"
destination_code = "Chatsworth Station - G Line (Orange)"
drop_off_type = "0"
pickup_type = "0"
route_code = "901"
stop_headsign = "901 - Chatsworth Station - G Line (Orange)"
stop_id = "15546"
stop_sequence = "5"
timepoint = "1"
trip_id = "60901000542140-JUNE22"
trip_id_event = "55763935-JUNE22-D08CAR-2_Saturday"
