arrival_time = "13:29:00"
departure_time = "13:29:00"
destination_code = "Harbor Freeway Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "81"
stop_headsign = "81 - Harbor Freeway Station"
stop_id = "13480"
stop_sequence = "57"
timepoint = "0"
trip_id = "10081003231206-JUNE22"
trip_id_event = "55895004-JUNE22-D03CAR-1_Weekday"
