arrival_time = "15:31:00"
departure_time = "15:31:00"
destination_code = "Vernon - Santa Fe"
drop_off_type = "1"
pickup_type = "1"
route_code = "105"
stop_headsign = "105 - Vernon - Santa Fe"
stop_id = "7099"
stop_sequence = "75"
timepoint = "1"
trip_id = "60105002581354-JUNE22"
trip_id_event = "55817372-JUNE22-D02CAR-2_Saturday"
