arrival_time = "05:16:00"
bay_num = "09 05"
departure_time = "05:16:00"
destination_code = "Downtown LA - Union Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "40"
stop_headsign = "40 - Downtown LA - Union Station"
stop_id = "30000"
stop_sequence = "80"
timepoint = "1"
trip_id = "10040009120403-JUNE22"
trip_id_event = "55939637-JUNE22-D18CAR-1_Weekday"
