arrival_time = "19:59:00"
departure_time = "19:59:00"
destination_code = "Westwood / UCLA"
drop_off_type = "0"
pickup_type = "0"
route_code = "2"
stop_headsign = "2 - Westwood / UCLA"
stop_id = "5149"
stop_sequence = "16"
timepoint = "0"
trip_id = "70002011241945-JUNE22"
trip_id_event = "55883856-JUNE22-D07CAR-3_Sunday"
