arrival_time = "06:50:00"
departure_time = "06:50:00"
destination_code = "Downtown LA - Grand - Venice"
drop_off_type = "0"
pickup_type = "0"
route_code = "76"
stop_headsign = "76 - Downtown LA - Grand - Venice"
stop_id = "10229"
stop_sequence = "27"
timepoint = "1"
trip_id = "10076001920625-JUNE22"
trip_id_event = "55850902-JUNE22-D09CAR-1_Weekday"
