arrival_time = "12:09:00"
departure_time = "12:09:00"
destination_code = "Sylmar Metrolink Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "236"
stop_headsign = "236 - Sylmar Metrolink Station"
stop_id = "342"
stop_sequence = "19"
timepoint = "0"
trip_id = "70236001351150-JUNE22"
trip_id_event = "55790967-JUNE22-D08CAR-3_Sunday"
