arrival_time = "07:04:00"
departure_time = "07:04:00"
destination_code = "Westlake / MacArthur Park Station"
drop_off_type = "0"
pickup_type = "0"
route_code = "51"
stop_headsign = "51 - Westlake / MacArthur Park Station"
stop_id = "15746"
stop_sequence = "52"
timepoint = "0"
trip_id = "10051003240614-JUNE22"
trip_id_event = "55982897-JUNE22-D02CAR-1_Weekday"
