arrival_time = "17:48:00"
departure_time = "17:48:00"
destination_code = "Downtown LA - 6th - Central"
drop_off_type = "0"
pickup_type = "0"
route_code = "720"
stop_headsign = "720 - Downtown LA - 6th - Central"
stop_id = "1212"
stop_sequence = "30"
timepoint = "1"
trip_id = "10720012811605-JUNE22"
trip_id_event = "55978577-JUNE22-D13CAR-1_Weekday"
