arrival_time = "09:54:00"
departure_time = "09:54:00"
destination_code = "Santa Monica (Rapid)"
drop_off_type = "0"
pickup_type = "0"
route_code = "720"
stop_headsign = "720 - Santa Monica (Rapid)"
stop_id = "16675"
stop_sequence = "26"
timepoint = "1"
trip_id = "10720012730830-JUNE22"
trip_id_event = "55978364-JUNE22-D13CAR-1_Weekday"
