arrival_time = "21:33:00"
departure_time = "21:33:00"
destination_code = "Eagle Rock Plaza"
drop_off_type = "0"
pickup_type = "0"
route_code = "81"
stop_headsign = "81 - Eagle Rock Plaza"
stop_id = "3512"
stop_sequence = "68"
timepoint = "0"
trip_id = "60081003222020-JUNE22"
trip_id_event = "55896425-JUNE22-D03CAR-2_Saturday"
